version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhl_server
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: dhl_db
      POSTGRES_USER: dhl_user
      POSTGRES_PASSWORD: dhl_pass
    networks:
      - dhl_net

  db:
    image: postgres:15
    container_name: dhl_db
    restart: always
    environment:
      POSTGRES_DB: dhl_db
      POSTGRES_USER: dhl_user
      POSTGRES_PASSWORD: dhl_pass
    ports:
      - "5432:5432"
    networks:
      - dhl_net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  dhl_net:

volumes:
  pgdata:
