services:
  db:
    image: postgres:15
    container_name: dhl_db
    restart: always
    environment:
      POSTGRES_DB: dhl_db
      POSTGRES_USER: dhl_user
      POSTGRES_PASSWORD: dhl_pass
    ports:
      - "5434:5432"
    networks:
      - dhl_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhl_user -d dhl_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: server
    container_name: dhl_server
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: dhl_db
      POSTGRES_USER: dhl_user
      POSTGRES_PASSWORD: dhl_pass
      CONFIG_PATH: /etc/server/config.json
    ports:
      - "9999:9999"
    volumes:
      - ./config/server_config.json:/etc/server/config.json
      - ./config/server:/etc/server/clients
    networks:
      - dhl_net
    command: ["/app/dhl_server"]

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: client
    container_name: dhl_clients
    depends_on:
      - server
    environment:
      - NUM_CLIENTS=${NUM_CLIENTS:-10}
      - CONFIG_BASE_PATH=/etc/client/client_%s.conf
      - LOG_DIR=/var/log/dhl
    networks:
      - dhl_net
    volumes:
      - ./config/clients:/etc/client/
      - ./scripts:/app/scripts
    command: ["/bin/bash", "/app/scripts/run_n_clients_docker.sh"]

networks:
  dhl_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.22.0.0/16
        - subnet: fd01::/64

volumes:
  pgdata:
