name: "Doc check"
description: "Code documentation generation with Doxygen"

runs:
  using: "composite"
  steps:
    - name: "Run doxygen command"
      shell: bash
      run: |
          DOX_CONF_FILE=$(pwd)/Doxyfile

          echo "Using: $DOX_CONF_FILE"
          cat $DOX_CONF_FILE

          ERROR_FILE_FLAG=dox_errors.txt
          doxygen -s "$DOX_CONF_FILE"

          # Verificamos si el archivo de errores existe y tiene contenido
          if [ -s "$ERROR_FILE_FLAG" ]; then
            echo "❌ Error: There are poorly documented files or warnings."
            cat "$ERROR_FILE_FLAG"
            exit 1
          else
            echo "✅ All documentation is correct."
            exit 0
          fi
    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Doxygen errors!!!
        path: $(pwd)/dox_errors.txt
        retention-days: 1